# Generated by Django 4.2.6 on 2023-11-01 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcategories',
            name='user',
            field=models.ManyToManyField(null=True, related_name='users_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
