# Generated by Django 4.2.6 on 2023-11-01 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_doctorcategories_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorcategories',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
