# Generated by Django 4.2.6 on 2023-11-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_doctorcategories_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is online or not'),
        ),
    ]
