# Generated by Django 4.2.6 on 2023-11-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_is_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_online',
            new_name='online_status',
        ),
    ]
