# Generated by Django 4.2.6 on 2023-11-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='news/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
