# Generated by Django 4.2.6 on 2023-11-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_news', '0002_drugs_baydrugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baydrugs',
            name='drugs_id',
        ),
        migrations.AddField(
            model_name='baydrugs',
            name='drugs_id',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
