# Generated by Django 4.1.12 on 2023-11-01 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_news', '0003_remove_baydrugs_drugs_id_baydrugs_drugs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baydrugs',
            name='count_drugs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baydrugs',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baydrugs',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='drugs/'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
