# Generated by Django 4.2.6 on 2023-11-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_news', '0004_alter_baydrugs_count_drugs_alter_baydrugs_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
