# Generated by Django 4.2.6 on 2023-11-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_news', '0005_alter_news_img'),
        ('shop_news', '0005_usercard'),
    ]

    operations = [
    ]
