<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-11-02 12:54
=======
# Generated by Django 4.2.6 on 2023-11-03 06:02
>>>>>>> c36e697f9c286948f9266a591f6d2fb6ecaa6cf7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_news', '0005_alter_news_img'),
        ('shop_news', '0005_usercard'),
    ]

    operations = [
    ]
