# Generated by Django 4.2.6 on 2023-11-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_news', '0006_merge_0005_alter_news_img_0005_usercard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(default=1, upload_to='news/'),
            preserve_default=False,
        ),
    ]
