# Generated by Django 4.2.6 on 2023-11-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_news', '0006_merge_0005_alter_news_img_0005_usercard'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='login_banner/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BannerMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='main_banner/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
