# Generated by Django 4.2.6 on 2023-10-17 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.UUID('99fc3512-5b6e-4a45-bbb0-db47b06fdd12'), editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product name')),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Product Image')),
                ('product_price', models.FloatField(blank=True, default=0, null=True, verbose_name='Product Price')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Create date')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
