# Generated by Django 4.2.6 on 2023-10-17 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_img',
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('a28b1388-4b06-4f5a-b6e3-062176f04cb9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
