# Generated by Django 4.2.6 on 2023-11-01 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consultation',
            table='Consultation',
        ),
    ]
