# Generated by Django 4.2.6 on 2023-11-01 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultation', '0002_alter_consultation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='appoint_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='appoint_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
